home="d:/asud"					#Корневой каталог сервера
location= "Asia/Omsk"   		#Временной пояс сервера
steppudge=1						#Шаг сохранения в pudge
#Описание параметров доступа к БД
[dataBase]
	host= "localhost"
	port= 5432
	user= "postgres"
	password= "162747"
	dbname= "agserv"
#Настройки сервера контроллеров
[commServer]
	port= 1093					#Основной порт связи
	portc= 2001					#Порт приема команд от сервера АРМ
	porta= 2002					#Порт приема массивов привязки от сервера АРМ
	read_timeout= 420			#Таймаут на ожидание сообщения от устройства  в секундах
	write_timeout= 40			#Таймаут на передачу команды в устройства
	id= 167						#ID сервера
#Настройки симулятора контроллеров
[controller]
	ip="localhost"				#IP сервера
	port=1093					#Порт 
	step=10						#Шаг симулятора в секундах
	guiport= 8080				
	random=true					#Если истина то случайно меняем состояние контроллера
