home="d:/asud"					#Корневой каталог сервера
location= "Asia/Omsk"   		#Временной пояс сервера
steppudge=1						#Шаг сохранения в pudge
#Описание параметров доступа к БД
[dataBase]
	host= "192.168.115.115"
	port= 5432
	user= "postgres"
	password= "162747"
	dbname= "agserv"
#Настройки сервера контроллеров
[commServer]
	port= 1093					#Основной порт связи
	portc= 2001					#Порт приема команд от сервера АРМ
	porta= 2002					#Порт приема массивов привязки от сервера АРМ
	portp= 2003					#Порт приема изменения протокола от сервера АРМ
	read_timeout= 420			#Таймаут на ожидание сообщения от устройства  в секундах
	write_timeout= 40			#Таймаут на передачу команды в устройства
	id= 167						#ID сервера
#Настройки симулятора контроллеров
[controller]
	ip="localhost"				#IP сервера
	port=1093					#Порт 
	step=10						#Шаг симулятора в секундах
	guiport= 8080				
	random=true					#Если истина то случайно меняем состояние контроллера
#Настройки системы управления по характерным точкам
[xctrl]
    switch=true         #Включить модуль управления по характерным точкам
    calculate=true      #Включить алгоритм расчета
	stepCalc=900		#Шаг расчетов характерных точек
	stepSend=300		#Шаг передачи результатов на устройства
[saver]
    remote="192.168.1.1:2005"
    file="result.sql"
    presql=[
        "delete from public.cross where region=1;",
        "delete from public.cross where region=2;",
        "delete from public.cross where region=3;",
        "delete from public.xctrl where region=1;",
        "delete from public.xctrl where region=2;",
        "delete from public.xctrl where region=3;",
        "delete from public.routes where region=1;",
        "delete from public.routes where region=2;",
        "delete from public.routes where region=3;"
    ]
    step=5         #Шаг проверки изменения в БД
    keys=[["cross","region","area","subarea","id"],
          ["devices","id"],
          ["region","region","area"],
          ["xctrl","region","area","subarea"],
          ["routes","region","id"]
         ]